/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 36
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_strategy = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_PARAM = 4,
  anon_sym_EQ = 5,
  anon_sym_NAME = 6,
  anon_sym_TYPE = 7,
  anon_sym_DOT = 8,
  anon_sym_LPAREN = 9,
  anon_sym_COMMA = 10,
  anon_sym_RPAREN = 11,
  sym_identifier = 12,
  sym_number = 13,
  sym_string = 14,
  anon_sym_SLASH_SLASH = 15,
  aux_sym_comment_token1 = 16,
  anon_sym_POUND = 17,
  sym_source_file = 18,
  sym_strategy_definition = 19,
  sym_parameter_definition = 20,
  sym_metadata_definition = 21,
  sym_assignment = 22,
  sym_expression = 23,
  sym_function_call = 24,
  sym_comment = 25,
  aux_sym_source_file_repeat1 = 26,
  aux_sym_strategy_definition_repeat1 = 27,
  aux_sym_function_call_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_strategy] = "strategy",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_PARAM] = "PARAM",
  [anon_sym_EQ] = "=",
  [anon_sym_NAME] = "NAME",
  [anon_sym_TYPE] = "TYPE",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_POUND] = "#",
  [sym_source_file] = "source_file",
  [sym_strategy_definition] = "strategy_definition",
  [sym_parameter_definition] = "parameter_definition",
  [sym_metadata_definition] = "metadata_definition",
  [sym_assignment] = "assignment",
  [sym_expression] = "expression",
  [sym_function_call] = "function_call",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_strategy_definition_repeat1] = "strategy_definition_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_strategy] = anon_sym_strategy,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_PARAM] = anon_sym_PARAM,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_NAME] = anon_sym_NAME,
  [anon_sym_TYPE] = anon_sym_TYPE,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_source_file] = sym_source_file,
  [sym_strategy_definition] = sym_strategy_definition,
  [sym_parameter_definition] = sym_parameter_definition,
  [sym_metadata_definition] = sym_metadata_definition,
  [sym_assignment] = sym_assignment,
  [sym_expression] = sym_expression,
  [sym_function_call] = sym_function_call,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_strategy_definition_repeat1] = aux_sym_strategy_definition_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_strategy] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PARAM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NAME] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TYPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_strategy_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_strategy_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_function = 1,
  field_left = 2,
  field_method = 3,
  field_name = 4,
  field_right = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_function] = "function",
  [field_left] = "left",
  [field_method] = "method",
  [field_name] = "name",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_value, 1},
  [1] =
    {field_name, 1},
  [2] =
    {field_name, 1},
    {field_value, 3},
  [4] =
    {field_left, 0},
    {field_right, 2},
  [6] =
    {field_function, 0},
    {field_method, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '"', 2,
        '#', 39,
        '(', 30,
        ')', 32,
        ',', 31,
        '.', 29,
        '/', 3,
        '=', 26,
        'N', 4,
        'P', 5,
        'T', 13,
        's', 18,
        '{', 23,
        '}', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '}') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(35);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(36);
      END_STATE();
    case 4:
      if (lookahead == 'A') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'A') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'A') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'E') ADVANCE(27);
      END_STATE();
    case 8:
      if (lookahead == 'E') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'M') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 'M') ADVANCE(25);
      END_STATE();
    case 11:
      if (lookahead == 'P') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == 'R') ADVANCE(6);
      END_STATE();
    case 13:
      if (lookahead == 'Y') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == 'g') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 20:
      if (lookahead == 'y') ADVANCE(22);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_strategy);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PARAM);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_NAME);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_TYPE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 37},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_strategy] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_PARAM] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_NAME] = ACTIONS(1),
    [anon_sym_TYPE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(28),
    [sym_strategy_definition] = STATE(2),
    [sym_parameter_definition] = STATE(2),
    [sym_metadata_definition] = STATE(2),
    [sym_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_strategy] = ACTIONS(5),
    [anon_sym_PARAM] = ACTIONS(7),
    [anon_sym_NAME] = ACTIONS(9),
    [anon_sym_TYPE] = ACTIONS(9),
    [anon_sym_SLASH_SLASH] = ACTIONS(11),
    [anon_sym_POUND] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(5), 1,
      anon_sym_strategy,
    ACTIONS(7), 1,
      anon_sym_PARAM,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 2,
      anon_sym_NAME,
      anon_sym_TYPE,
    ACTIONS(11), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
    STATE(3), 5,
      sym_strategy_definition,
      sym_parameter_definition,
      sym_metadata_definition,
      sym_comment,
      aux_sym_source_file_repeat1,
  [25] = 6,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_strategy,
    ACTIONS(20), 1,
      anon_sym_PARAM,
    ACTIONS(23), 2,
      anon_sym_NAME,
      anon_sym_TYPE,
    ACTIONS(26), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
    STATE(3), 5,
      sym_strategy_definition,
      sym_parameter_definition,
      sym_metadata_definition,
      sym_comment,
      aux_sym_source_file_repeat1,
  [50] = 1,
    ACTIONS(29), 7,
      ts_builtin_sym_end,
      anon_sym_strategy,
      anon_sym_PARAM,
      anon_sym_NAME,
      anon_sym_TYPE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
  [60] = 1,
    ACTIONS(31), 7,
      ts_builtin_sym_end,
      anon_sym_strategy,
      anon_sym_PARAM,
      anon_sym_NAME,
      anon_sym_TYPE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
  [70] = 1,
    ACTIONS(33), 7,
      ts_builtin_sym_end,
      anon_sym_strategy,
      anon_sym_PARAM,
      anon_sym_NAME,
      anon_sym_TYPE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
  [80] = 1,
    ACTIONS(35), 7,
      ts_builtin_sym_end,
      anon_sym_strategy,
      anon_sym_PARAM,
      anon_sym_NAME,
      anon_sym_TYPE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
  [90] = 1,
    ACTIONS(37), 7,
      ts_builtin_sym_end,
      anon_sym_strategy,
      anon_sym_PARAM,
      anon_sym_NAME,
      anon_sym_TYPE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
  [100] = 4,
    ACTIONS(39), 1,
      sym_identifier,
    STATE(18), 1,
      sym_function_call,
    STATE(19), 1,
      sym_expression,
    ACTIONS(41), 2,
      sym_number,
      sym_string,
  [114] = 3,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    ACTIONS(45), 1,
      sym_identifier,
    STATE(11), 2,
      sym_assignment,
      aux_sym_strategy_definition_repeat1,
  [125] = 3,
    ACTIONS(45), 1,
      sym_identifier,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(12), 2,
      sym_assignment,
      aux_sym_strategy_definition_repeat1,
  [136] = 3,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(51), 1,
      sym_identifier,
    STATE(12), 2,
      sym_assignment,
      aux_sym_strategy_definition_repeat1,
  [147] = 2,
    ACTIONS(56), 1,
      anon_sym_DOT,
    ACTIONS(54), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [155] = 3,
    ACTIONS(58), 1,
      anon_sym_COMMA,
    ACTIONS(60), 1,
      anon_sym_RPAREN,
    STATE(15), 1,
      aux_sym_function_call_repeat1,
  [165] = 3,
    ACTIONS(58), 1,
      anon_sym_COMMA,
    ACTIONS(62), 1,
      anon_sym_RPAREN,
    STATE(16), 1,
      aux_sym_function_call_repeat1,
  [175] = 3,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
    STATE(16), 1,
      aux_sym_function_call_repeat1,
  [185] = 1,
    ACTIONS(69), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [190] = 1,
    ACTIONS(54), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [195] = 1,
    ACTIONS(71), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [200] = 2,
    ACTIONS(73), 1,
      anon_sym_RPAREN,
    ACTIONS(75), 1,
      sym_number,
  [207] = 1,
    ACTIONS(77), 2,
      sym_number,
      sym_string,
  [212] = 1,
    ACTIONS(79), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [217] = 1,
    ACTIONS(81), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [222] = 1,
    ACTIONS(67), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [227] = 1,
    ACTIONS(83), 1,
      anon_sym_EQ,
  [231] = 1,
    ACTIONS(85), 1,
      aux_sym_comment_token1,
  [235] = 1,
    ACTIONS(87), 1,
      sym_identifier,
  [239] = 1,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
  [243] = 1,
    ACTIONS(91), 1,
      sym_string,
  [247] = 1,
    ACTIONS(93), 1,
      sym_identifier,
  [251] = 1,
    ACTIONS(95), 1,
      anon_sym_LPAREN,
  [255] = 1,
    ACTIONS(97), 1,
      sym_number,
  [259] = 1,
    ACTIONS(99), 1,
      anon_sym_EQ,
  [263] = 1,
    ACTIONS(101), 1,
      sym_identifier,
  [267] = 1,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 25,
  [SMALL_STATE(4)] = 50,
  [SMALL_STATE(5)] = 60,
  [SMALL_STATE(6)] = 70,
  [SMALL_STATE(7)] = 80,
  [SMALL_STATE(8)] = 90,
  [SMALL_STATE(9)] = 100,
  [SMALL_STATE(10)] = 114,
  [SMALL_STATE(11)] = 125,
  [SMALL_STATE(12)] = 136,
  [SMALL_STATE(13)] = 147,
  [SMALL_STATE(14)] = 155,
  [SMALL_STATE(15)] = 165,
  [SMALL_STATE(16)] = 175,
  [SMALL_STATE(17)] = 185,
  [SMALL_STATE(18)] = 190,
  [SMALL_STATE(19)] = 195,
  [SMALL_STATE(20)] = 200,
  [SMALL_STATE(21)] = 207,
  [SMALL_STATE(22)] = 212,
  [SMALL_STATE(23)] = 217,
  [SMALL_STATE(24)] = 222,
  [SMALL_STATE(25)] = 227,
  [SMALL_STATE(26)] = 231,
  [SMALL_STATE(27)] = 235,
  [SMALL_STATE(28)] = 239,
  [SMALL_STATE(29)] = 243,
  [SMALL_STATE(30)] = 247,
  [SMALL_STATE(31)] = 251,
  [SMALL_STATE(32)] = 255,
  [SMALL_STATE(33)] = 259,
  [SMALL_STATE(34)] = 263,
  [SMALL_STATE(35)] = 267,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata_definition, 2, 0, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strategy_definition, 5, 0, 2),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strategy_definition, 4, 0, 2),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_definition, 4, 0, 3),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_strategy_definition_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strategy_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, 0, 5),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 4),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 6, 0, 5),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 7, 0, 5),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [89] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_trading_dsl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
